### ISSUE TITLE
npm ERR! code 1 when gulp task 'karma:single-run' fails

### ISSUE THREAD

**Issue by kimbaudi** [FountainJS/generator-fountain-karma#43]
Failing a test after executing `gulp task 'karma:single-run'` returns `npm ERR! Exit status 1`. The reason this is happening is because of `karmaFinishHandler()` function in `gulp_tasks/karma.js`.

**Problem code:**
```js
function karmaFinishHandler(done) {
  return failCount => {
    done(failCount ? new Error(`Failed ${failCount} tests.`) : null);
  };
}
```
Whenever `failCount` is truthy, 'karma:single-run' errors. This only happens for 'karma:single-run' (not an issue with 'karma:auto-run')

**Simple fix:**

```js
function karmaFinishHandler(done) {
  return () => {
    done();
  };
}
```

## Reproduce
- scaffold angular 2 app using FountainJS
```shell
paul@mars:~/Development/test$ yo fountain-webapp

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │    Welcome to Yeoman,    │
   `---------´   │   ladies and gentlemen!  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include by default Gulp 4, ESLint, Browsersync and Karma.

? Which JavaScript framework do you want? Angular 2
? Which module management do you want? Webpack with NPM
? Which JS preprocessor do you want? TypeScript
? Which CSS preprocessor do you want? SASS
? Which Continuous Integration platform do you want? Travis
? Do you want a sample app? A working landing page
? Would you like a router? @angular/router
```
- open `/src/app/header.html` and edit text "Fountain Generator" to something else (i.e., "Fountain Generator rocks!" so that karma test fails

- open terminal and enter `npm run test` to execute `gulp test` (which in turn executes gulp task `'karma:single-run'`)

## Result

```shell
paul@mars:~/Development/test$ npm run test

> @ test /home/paul/Development/test
> gulp test

[11:46:56] Loading /home/paul/Development/test/gulp_tasks/browsersync.js
[11:46:56] Loading /home/paul/Development/test/gulp_tasks/karma.js
[11:46:57] Loading /home/paul/Development/test/gulp_tasks/misc.js
[11:46:57] Loading /home/paul/Development/test/gulp_tasks/webpack.js
[11:46:57] Using gulpfile ~/Development/test/gulpfile.js
[11:46:57] Starting 'test'...
[11:46:57] Starting 'karma:single-run'...
ts-loader: Using typescript@2.0.10 and /home/paul/Development/test/tsconfig.json
25 11 2016 11:47:05.878:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
25 11 2016 11:47:05.879:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 11 2016 11:47:05.964:INFO [launcher]: Starting browser Chrome
25 11 2016 11:47:09.079:INFO [Chrome 54.0.2840 (Linux 0.0.0)]: Connected on socket /#8LyRLrlxOlZiNbf4AAAA with id 72959560
Chrome 54.0.2840 (Linux 0.0.0) header component should render 'Fountain Generator' FAILED
	Expected 'Fountain Generator rocks!' to be 'Fountain Generator'.
	    at Object.<anonymous> (src/index.spec.js:42307:62)
	    at ZoneDelegate.invoke (src/index.spec.js:51054:26)
	    at ProxyZoneSpec.onInvoke (src/index.spec.js:50718:39)
	    at ZoneDelegate.invoke (src/index.spec.js:51053:32)
	    at Zone.run (src/index.spec.js:50936:43)
	    at Object.<anonymous> (src/index.spec.js:50433:34)
	    at src/index.spec.js:4456:21
	    at ZoneDelegate.invoke (src/index.spec.js:51054:26)
	    at AsyncTestZoneSpec.onInvoke (src/index.spec.js:50023:39)
	    at ProxyZoneSpec.onInvoke (src/index.spec.js:50715:39)
	    at ZoneDelegate.invoke (src/index.spec.js:51053:32)
	    at Zone.run (src/index.spec.js:50936:43)
	    at AsyncTestZoneSpec._finishCallback (src/index.spec.js:4451:29)
	    at src/index.spec.js:50012:31
	    at ZoneDelegate.invokeTask (src/index.spec.js:51087:35)
	    at Zone.runTask (src/index.spec.js:50976:47)
	    at ZoneTask.invoke (src/index.spec.js:51157:33)
	    at data.args.(anonymous function) (src/index.spec.js:51792:25)
Chrome 54.0.2840 (Linux 0.0.0): Executed 7 of 7 (1 FAILED) (0.829 secs / 0.778 secs)
[11:47:11] 'karma:single-run' errored after 13 s
[11:47:11] Error: Failed 1 tests.
    at failCount (/home/paul/Development/test/gulp_tasks/karma.js:13:22)
    at removeAllListeners (/home/paul/Development/test/node_modules/karma/lib/server.js:379:7)
    at Server.<anonymous> (/home/paul/Development/test/node_modules/karma/lib/server.js:390:9)
    at Server.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1544:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[11:47:11] 'test' errored after 13 s

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/paul/.nvm/versions/node/v7.2.0/bin/node" "/home/paul/.nvm/versions/node/v7.2.0/bin/npm" "run" "test"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ test: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script 'gulp test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/paul/Development/test/npm-debug.log
paul@mars:~/Development/test$ 
```

## Environment

```
ubuntu 16.04 LTS
node -v 7.2.0
npm -v 3.10.9
yo -v 1.8.5
generator-fountain-webapp -v 1.0.0-rc1
```

**Comment by micaelmbagira** [comment]
`Expected 'Fountain Generator rocks!' to be 'Fountain Generator'.`
